version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: "postgres:15.4-alpine"
    container_name: limeapi_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    image: limeapi  # ✅ Explicitly sets the image name
    build:
      context: .
      dockerfile: Dockerfile
    container_name: limeapi
    # restart: always
    # stdin_open: true
    # tty: true
    depends_on:
      - db
    environment:
      API_PORT: 3000
      ETH_NODE_URL: https://mainnet.infura.io/v3/28d8b996e9174e82a7d049f4198deed1
      JWT_SECRET: ${JWT_SECRET:-1234567890}
      DB_CONNECTION_URL: postgresql://postgres:postgres@db:5432/postgres
    entrypoint: ["./wait-for-it.sh", "db:5432", "--", "./limeapi"]
    # entrypoint: ["./limeapi"]
    ports:
      - "3000:3000"